name: Test

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-v00

      - name: Install flit and tox-related libs
        run: |
          python -m pip install --upgrade pip
          pip install flit tox tox-gh-actions

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: flit install --symlink

      - name: Lint
        run: bash ./scripts/lint.sh

      - name: Test
        run: bash ./scripts/test.sh

      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.1
